"""RAG Knowledge Assistant — friendly UI layer.

Welcome tour, plain-language explanations, and an honesty box adapted to
the chat layout (an expander instead of a tab). Streamlit only — no other
dependencies. Same pattern as Mandate's friendly UI, in this project's
voice: written for someone who has to answer questions about the EU AI Act.
"""

import streamlit as st

_TOUR_KEY = "rag_tour_done"


# ------------------------------------------------------------------ welcome
def show_welcome() -> bool:
    """One-time plain-language tour. Returns True once dismissed."""
    if st.session_state.get(_TOUR_KEY):
        return True

    _, mid, _ = st.columns([1, 2.6, 1])
    with mid:
        st.title("🔎 RAG Knowledge Assistant")
        st.subheader("An assistant that shows its sources — or says it doesn't know.")
        st.markdown(
            """
The EU AI Act is 180 pages of law. This assistant answers questions
about it by **retrieving the actual passages first** and only then
writing an answer — every claim carries a citation you can open and
read. If the retrieved text doesn't actually answer your question, it
**refuses instead of guessing**. That refusal is a feature, and it is
measured.

**What you can do here**

- Ask anything about the **EU AI Act** (Regulation (EU) 2024/1689) in
  the chat box — or click a sample question in the sidebar.
- Open **"Show retrieved context"** under any answer to read the exact
  passages the answer was built from, with similarity scores.
- Open **"How this works & the honesty box"** under the title for the
  pipeline in plain language and this system's measured limits.

**What this will not do**

It is not legal advice, and it answers only from the Act's text. Ask it
about cooking and it should politely refuse — that behaviour is part of
the evaluation suite.
"""
        )
        c1, c2 = st.columns(2)
        if c1.button("Start asking", type="primary", use_container_width=True):
            st.session_state[_TOUR_KEY] = True
            st.rerun()
        if c2.button("Skip the intro", use_container_width=True):
            st.session_state[_TOUR_KEY] = True
            st.rerun()
    return False


def show_replay() -> None:
    """Small sidebar control to replay the intro tour."""
    if st.button("↻ Replay the intro", use_container_width=True):
        st.session_state[_TOUR_KEY] = False
        st.rerun()


# ------------------------------------------------------------------ help
def show_help_expander() -> None:
    """How-it-works + honesty box, as an expander under the title."""
    with st.expander("❓ How this works & the honesty box"):
        st.markdown(
            """
#### How it works, in one breath

Your question is **rewritten** for better search, the most relevant
passages of the Act are **retrieved** from a local vector index, a
**grading step** checks whether those passages actually answer the
question, and only then is an answer **generated — with citations**. If
the grade says the context is insufficient, the assistant **refuses**
rather than improvising. The whole flow is a LangGraph workflow; the
embeddings are local; the language model is swappable (Groq by default).

#### Words on the screen, in plain language

- **Chunks** — the retrieved passages of the Act; open them to check
  any answer yourself.
- **Similarity** — how close a passage is to your question in the
  embedding space (higher = more relevant, not a guarantee of truth).
- **Citations** — the article/recital references each answer stands on.
- **Refusal** — the assistant declining to answer when the retrieved
  text doesn't support one. Measured on purpose-built out-of-scope
  questions.

#### The honesty box

- **Grounded ≠ guaranteed correct.** Answers are built from retrieved
  passages, but retrieval can miss the best passage — the citations
  exist so you can verify, and you should for anything that matters.
- **The evaluation is real but small:** a hand-written test set
  (including out-of-scope questions that must be refused) measuring
  retrieval precision, answer faithfulness, and refusal accuracy — the
  live results are committed in `evaluation/results.md`, regenerated by
  `make eval`.
- **The live answers need an API key** (`GROQ_API_KEY`); free-tier
  token quotas are real, and the eval is budgeted to fit inside them.
- **Not legal advice.** It cites the law; it does not interpret your
  situation.

[GitHub repository](https://github.com/hugocorreia123/rag-knowledge-assistant)
· Hugo Correia — [LinkedIn](https://www.linkedin.com/in/hugogncorreia)
"""
        )
